### PR TITLE
Add product tags

### LINKED ISSUE #63: Difference between ParentId and ParentCategoryId in Category model?
1. What's the difference between ParentId and ParentCategoryId in `EasyAbp.EShop.Products.CategoriesCategory`?
1. Which should be used?

### LINKED ISSUE #64: Implementation of store's categories
How to implement categories belongs to store, like this:
image

I think the solution maybe be one of:
1. add `StoreId` to `Category` and add related CRUD interfaces.
1. create new type like `StoreCategory` and add related CRUD interfaces.

What do you think @gdlcf88 ?

### PR DESCRIPTION
**Pull request by RayMMond**
Resolve #64, #63.

### CODE REVIEW

**Comment by gdlcf88** [comment]
Hi @RayMMond, could you please also implement these features?

* MVC UI: ProductTags select in create product modal and edit product modal.
* MVC UI: Tag management pages.

**Comment by RayMMond** [comment]
1. I'm working on that.
2. It needs #68 to handle permission correctly.

**Comment by gdlcf88** [comment]
> It needs #68 to handle permission correctly

Product management pages are for store-side admin too, #68 doesn't affect the implementation of the tag management pages.

**Comment by gdlcf88** [comment]
Hi @RayMMond, I see this PR has been around for some time, could you please finish the rest of the work?

Some tips:
1. #63 has been done by https://github.com/EasyAbp/EShop/commit/518d3b0b125809bb9f92efc98326d0dfba3654a2, so the migration files and some code changes in this PR should be handle.
2. Modules of EasyAbp do not need the auto API controller anymore, so we should create a `ProductTagController` for `ProductTagAppService`, you can do it with AbpHelper's new controller generation feature. (refer to https://github.com/EasyAbp/EShop/commit/6b3dfa8f44a98511bb8c69b2c5e55d6f0bcebdec#diff-2404d1e57687ecd2ff7b6869aca7108a)
3. Should finish ProductTag's management pages, I can help you if you need it.

**Comment by RayMMond** [comment]
@gdlcf88 Sorry~ super busy last two weeks 😂 , I will try to finish this PR this weekend. 
About management pages, honestly, I'm not vary good at MVCs, but I still wanna try it first, so If I can't finish it by the end of week, I will ask for help 😄

**Comment by wakuflair** [comment]
Is there any possibility that extract "tag" feature into separate module?

**Comment by RayMMond** [comment]
@gdlcf88 I have finished this PR, you can review it now. 😃

**Comment by RayMMond** [comment]
@wakuflair I think tag feature could be a plugin module, but I haven't checked the code of plugins.
What do you think @gdlcf88 ?

**Comment by gdlcf88** [comment]
> @wakuflair I think tag feature could be a plugin module, but I haven't checked the code of plugins.
> What do you think @gdlcf88 ?

Agree. 

I think it will depend on the unfinished design of EShop.Plugins module. Think about this: how to insert widgets of the ProductTag plugin into the product management page?

Maybe there are some other works that should be done:
1. Make EShop.Products.Web depends on EShop.Plugins.Web
2. Design some "plugins hooks", for example:
    * Load extra entries in the action dropdown menu of the product list page.
    * Load extra widgets in the product's create/edit/(detail)/createSku/editSku/(skuDetail) modals. (refer to abp's [Login.cshtml](https://github.com/abpframework/abp/blob/3.0.4/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml#L50))

Does anyone else have a better idea?

**Comment by RayMMond** [comment]
@gdlcf88 @wakuflair maybe the tag feature should be implemented in another PR?

**Comment by gdlcf88** [comment]
> @gdlcf88 @wakuflair maybe the tag feature should be implemented in another PR?

If the above consideration is reasonable, creating a new PR based on the latest dev branch may be better. 🤣

**Comment by RayMMond** [comment]
@gdlcf88 Can you resent a invitation of EasyAbp team? Last one is expired...

**Comment by RayMMond** [comment]
Make product tag as plugin, close this.

**Pull request closed without merging**
